### ISSUE TITLE
can not read the .ctl file with %fhn

### ISSUE THREAD

**Issue by xigrug** [miniufo/xgrads#38]
`dset ^chemvar20220101000%fhn
options  little_endian template
title model mpi IO output from nwp
undef 9.999E+20
xdef  751 linear   70.0000    0.1000
ydef  501 linear   15.0000    0.1000
zdef   51 linear 1 1
tdef    73 linear 00Z01JAN2022    60mn
vars 26

endvars`

with the output is 

> <Exception: unsupported format: %fh>

**Comment by miniufo** [comment]
Hi, I would like to add support for `%fh` but I don't have those sample files for test.  Could you please send me some example files?  Maybe in .zip file if there are more than one file.

**Comment by xigrug** [comment]
Thank you. I have sent the files to your 163 email.

> Hi, I would like to add support for `%fh` but I don't have those sample files for test. Could you please send me some example files? Maybe in .zip file if there are more than one file.

**Comment by miniufo** [comment]
Hi, I can only download 1GB of the data and then the connection is cut.  Can you send the data to my email using "超大附件"?
![image](https://user-images.githubusercontent.com/9312831/184110141-e55a16cc-a069-4c0f-8346-c27e63ab8db4.png)

**Comment by miniufo** [comment]
I've made a fix and please update the codes to try if there is any problem.

Note that `GrADS` will plot `nan` if a forecast time file is missing.  Here for simplicity, `xgrads` will raise an error if some of the forecast files are missing.  For your example, if the basetime is `00Z01JAN2022` with 3 forecast times of interval `1hr` (or `60mn`), we expect `chemvar202201010000000`, `chemvar202201010000100`, and `chemvar202201010000200` three files.

If you only have two files `chemvar202201010000100` and `chemvar202201010000200`, please change the basetime to `01Z01JAN2022` and set time steps as `2` in your ctl.

Please tell me if this does not work.

**Comment by xigrug** [comment]
I have tried the  open_mfdataset and open_ctldataset. It is failed with  _Exception: unsupported format: %fh. 
>>> ds=open_mfdataset("chem_ori.ctl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/io.py", line 68, in open_mfdataset
    datasets = [open_(p, encoding=encoding) for p in paths]
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/io.py", line 68, in <listcomp>
    datasets = [open_(p, encoding=encoding) for p in paths]
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/io.py", line 107, in open_CtlDataset
    ctl = CtlDescriptor(encoding=encoding, file=desfile)
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 167, in __init__
    self.parse(fileContent)
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 211, in parse
    self._processDSets(dpath_str)
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 233, in _processDSets
    tokens.append(self._get_template_format(token))
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 564, in _get_template_format
    raise Exception('unsupported format: ' + part)
Exception: unsupported format: %fh

>>> ds=open_ctldataset("chem_ori.ctl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'open_ctldataset' is not defined
>>> ds=open_CtlDataset("chem_ori.ctl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/io.py", line 107, in open_CtlDataset
    ctl = CtlDescriptor(encoding=encoding, file=desfile)
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 167, in __init__
    self.parse(fileContent)
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 211, in parse
    self._processDSets(dpath_str)
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 233, in _processDSets
    tokens.append(self._get_template_format(token))
  File "/g3/liuchong/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 564, in _get_template_format
    raise Exception('unsupported format: ' + part)
Exception: unsupported format: %fh

**Comment by miniufo** [comment]
There is no `%fh`.  Available one are:
![image](https://user-images.githubusercontent.com/9312831/186121772-9b1c356f-7f7f-4ff4-ad89-770ff418c2c5.png)

![image](https://user-images.githubusercontent.com/9312831/186121973-b43b33d2-c866-460f-8458-55f74456624a.png)


Not sure if `%fh` is supported by `GrADS`...

**Comment by xigrug** [comment]
Yes, but my .ctl is "dset ^chemvar20220101000%fhn"

the output said "Exception: unsupported format: %fh"

**Comment by miniufo** [comment]
I tried again with your ctl and data and everything works fine.  Maybe you can use `print(part)` in `_get_template_format` in the source code to see what is wrong here.  You may also use wechat for a more direct discussion (my is 13631383406).

I am not sure about the tailing characters.  My rule is that if `GrADS` can then `xgrads` can do it too.  So you can try with it using `GrADS`.

**Comment by JQQQQQQ** [comment]
楼主，你好。请问这个问题解决了嘛？我也遇到了和你一样的问题，读取chemvar.ctl时说是识别不了%fh。想请教你一下。

**Comment by JQQQQQQ** [comment]
Hello landlord. Is this problem solved? I also had the same problem as you, reading chemvar.ctl and saying that %fh was not recognized. I would like to ask you about it.

**Comment by miniufo** [comment]
请问有没有用最新的代码测试？或者加我的微信13631383406用你的数据测试一下
